<h1>Détail de la commande <?= $order[0]['orderNumber'] ?></h1>


<table class="table table-striped">
    <thead>
        <tr>
            <th>Produit</th>
            <th>Prix unitaire</th>
            <th>Quantité</th>
            <th>Sous-total</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($order as $orderdetail): ?>
            <tr>
                <td><?= $orderdetail['productName'] ?></td>
                <td><?= $orderdetail['priceEach'] ?></td>
                <td><?= $orderdetail['quantityOrdered'] ?></td>
                <td><?= $orderdetail['subTotal'] ?></td>
            </tr>
        <?php endforeach ?>
    </tbody>
    <tfoot>
        <tr>
            <th colspan="3">Total de la commande</th>
            <th><?= $total ?></th>
        </tr>
    </tfoot>
</table>